/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CashflowEntry {
  'id' : bigint,
  'entryType' : EntryType,
  'userId' : Principal,
  'date' : bigint,
  'entryLabel' : string,
  'amount' : number,
}
export type CommunityChannel = { 'general' : null } |
  { 'announcements' : null };
export interface CommunityMessage {
  'id' : bigint,
  'authorUsername' : string,
  'content' : string,
  'timestamp' : bigint,
  'imageId' : [] | [string],
  'channel' : CommunityChannel,
  'authorPrincipal' : Principal,
}
export interface DirectMessage {
  'id' : bigint,
  'content' : string,
  'toPrincipal' : Principal,
  'fromPrincipal' : Principal,
  'timestamp' : bigint,
  'fromUsername' : string,
  'imageId' : [] | [string],
}
export type EntryType = { 'expense' : null } |
  { 'investment' : null } |
  { 'income' : null };
export interface Habit {
  'id' : bigint,
  'completions' : Array<bigint>,
  'userId' : Principal,
  'name' : string,
  'createdAt' : bigint,
}
export interface Task {
  'id' : bigint,
  'title' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'completed' : boolean,
}
export interface UserProfile {
  'username' : string,
  'displayName' : string,
  'avatarId' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCashflowEntry' : ActorMethod<[EntryType, string, number, bigint], bigint>,
  'addHabit' : ActorMethod<[string], bigint>,
  'addTask' : ActorMethod<[string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeTask' : ActorMethod<[bigint], boolean>,
  'deleteCashflowEntry' : ActorMethod<[bigint], boolean>,
  'deleteHabit' : ActorMethod<[bigint], boolean>,
  'deleteTask' : ActorMethod<[bigint], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCashflowEntries' : ActorMethod<[], Array<CashflowEntry>>,
  'getCashflowSummary' : ActorMethod<
    [],
    {
      'totalIncome' : number,
      'totalInvestments' : number,
      'totalExpenses' : number,
      'savings' : number,
    }
  >,
  'getChannelMessages' : ActorMethod<
    [CommunityChannel],
    Array<CommunityMessage>
  >,
  'getConversationList' : ActorMethod<
    [],
    Array<
      {
        'otherUsername' : string,
        'lastMessage' : string,
        'timestamp' : bigint,
        'otherPrincipal' : Principal,
      }
    >
  >,
  'getDirectMessages' : ActorMethod<[Principal], Array<DirectMessage>>,
  'getHabits' : ActorMethod<[], Array<Habit>>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getUserList' : ActorMethod<
    [],
    Array<
      {
        'principal' : Principal,
        'username' : string,
        'displayName' : string,
        'avatarId' : [] | [string],
      }
    >
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWealthGoal' : ActorMethod<[], [] | [number]>,
  'getWealthProgress' : ActorMethod<
    [],
    { 'goal' : number, 'currentSavings' : number, 'percentage' : number }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFounder' : ActorMethod<[], boolean>,
  'markHabitComplete' : ActorMethod<[bigint, bigint], boolean>,
  'postToChannel' : ActorMethod<
    [CommunityChannel, string, [] | [string]],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendDirectMessage' : ActorMethod<[Principal, string, [] | [string]], bigint>,
  'setWealthGoal' : ActorMethod<[number], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];