/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const EntryType = IDL.Variant({
  'expense' : IDL.Null,
  'investment' : IDL.Null,
  'income' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'avatarId' : IDL.Opt(IDL.Text),
});
export const CashflowEntry = IDL.Record({
  'id' : IDL.Nat,
  'entryType' : EntryType,
  'userId' : IDL.Principal,
  'date' : IDL.Int,
  'entryLabel' : IDL.Text,
  'amount' : IDL.Float64,
});
export const CommunityChannel = IDL.Variant({
  'general' : IDL.Null,
  'announcements' : IDL.Null,
});
export const CommunityMessage = IDL.Record({
  'id' : IDL.Nat,
  'authorUsername' : IDL.Text,
  'content' : IDL.Text,
  'timestamp' : IDL.Int,
  'imageId' : IDL.Opt(IDL.Text),
  'channel' : CommunityChannel,
  'authorPrincipal' : IDL.Principal,
});
export const DirectMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'toPrincipal' : IDL.Principal,
  'fromPrincipal' : IDL.Principal,
  'timestamp' : IDL.Int,
  'fromUsername' : IDL.Text,
  'imageId' : IDL.Opt(IDL.Text),
});
export const Habit = IDL.Record({
  'id' : IDL.Nat,
  'completions' : IDL.Vec(IDL.Int),
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'completed' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCashflowEntry' : IDL.Func(
      [EntryType, IDL.Text, IDL.Float64, IDL.Int],
      [IDL.Nat],
      [],
    ),
  'addHabit' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'addTask' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeTask' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteCashflowEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteHabit' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteTask' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCashflowEntries' : IDL.Func([], [IDL.Vec(CashflowEntry)], ['query']),
  'getCashflowSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalIncome' : IDL.Float64,
          'totalInvestments' : IDL.Float64,
          'totalExpenses' : IDL.Float64,
          'savings' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getChannelMessages' : IDL.Func(
      [CommunityChannel],
      [IDL.Vec(CommunityMessage)],
      ['query'],
    ),
  'getConversationList' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'otherUsername' : IDL.Text,
            'lastMessage' : IDL.Text,
            'timestamp' : IDL.Int,
            'otherPrincipal' : IDL.Principal,
          })
        ),
      ],
      ['query'],
    ),
  'getDirectMessages' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DirectMessage)],
      ['query'],
    ),
  'getHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUserList' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'principal' : IDL.Principal,
            'username' : IDL.Text,
            'displayName' : IDL.Text,
            'avatarId' : IDL.Opt(IDL.Text),
          })
        ),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWealthGoal' : IDL.Func([], [IDL.Opt(IDL.Float64)], ['query']),
  'getWealthProgress' : IDL.Func(
      [],
      [
        IDL.Record({
          'goal' : IDL.Float64,
          'currentSavings' : IDL.Float64,
          'percentage' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFounder' : IDL.Func([], [IDL.Bool], ['query']),
  'markHabitComplete' : IDL.Func([IDL.Nat, IDL.Int], [IDL.Bool], []),
  'postToChannel' : IDL.Func(
      [CommunityChannel, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendDirectMessage' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'setWealthGoal' : IDL.Func([IDL.Float64], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const EntryType = IDL.Variant({
    'expense' : IDL.Null,
    'investment' : IDL.Null,
    'income' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'avatarId' : IDL.Opt(IDL.Text),
  });
  const CashflowEntry = IDL.Record({
    'id' : IDL.Nat,
    'entryType' : EntryType,
    'userId' : IDL.Principal,
    'date' : IDL.Int,
    'entryLabel' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const CommunityChannel = IDL.Variant({
    'general' : IDL.Null,
    'announcements' : IDL.Null,
  });
  const CommunityMessage = IDL.Record({
    'id' : IDL.Nat,
    'authorUsername' : IDL.Text,
    'content' : IDL.Text,
    'timestamp' : IDL.Int,
    'imageId' : IDL.Opt(IDL.Text),
    'channel' : CommunityChannel,
    'authorPrincipal' : IDL.Principal,
  });
  const DirectMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'toPrincipal' : IDL.Principal,
    'fromPrincipal' : IDL.Principal,
    'timestamp' : IDL.Int,
    'fromUsername' : IDL.Text,
    'imageId' : IDL.Opt(IDL.Text),
  });
  const Habit = IDL.Record({
    'id' : IDL.Nat,
    'completions' : IDL.Vec(IDL.Int),
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'completed' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCashflowEntry' : IDL.Func(
        [EntryType, IDL.Text, IDL.Float64, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'addHabit' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'addTask' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeTask' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteCashflowEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteHabit' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteTask' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCashflowEntries' : IDL.Func([], [IDL.Vec(CashflowEntry)], ['query']),
    'getCashflowSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalIncome' : IDL.Float64,
            'totalInvestments' : IDL.Float64,
            'totalExpenses' : IDL.Float64,
            'savings' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getChannelMessages' : IDL.Func(
        [CommunityChannel],
        [IDL.Vec(CommunityMessage)],
        ['query'],
      ),
    'getConversationList' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'otherUsername' : IDL.Text,
              'lastMessage' : IDL.Text,
              'timestamp' : IDL.Int,
              'otherPrincipal' : IDL.Principal,
            })
          ),
        ],
        ['query'],
      ),
    'getDirectMessages' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DirectMessage)],
        ['query'],
      ),
    'getHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUserList' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'principal' : IDL.Principal,
              'username' : IDL.Text,
              'displayName' : IDL.Text,
              'avatarId' : IDL.Opt(IDL.Text),
            })
          ),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWealthGoal' : IDL.Func([], [IDL.Opt(IDL.Float64)], ['query']),
    'getWealthProgress' : IDL.Func(
        [],
        [
          IDL.Record({
            'goal' : IDL.Float64,
            'currentSavings' : IDL.Float64,
            'percentage' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFounder' : IDL.Func([], [IDL.Bool], ['query']),
    'markHabitComplete' : IDL.Func([IDL.Nat, IDL.Int], [IDL.Bool], []),
    'postToChannel' : IDL.Func(
        [CommunityChannel, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendDirectMessage' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'setWealthGoal' : IDL.Func([IDL.Float64], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };